### PR TITLE
Readme/12 pocketbase vue starter

### PR DESCRIPTION
**Pull request by MRSessions**
#12

### CODE REVIEW

**Review by benallfree — CHANGES_REQUESTED** [review]
1. Let's keep this PR open until `WIP` is removed. After all, this is *awesome*-pocketbase :)
2. I'm not clear on what you mean by `served from PocketBase (used as a Go framework/toolkit) as a backend`. Is that different from `served from PocketBase`?

**Comment by benallfree** [comment]
Also, just out of curiosity, why the custom build of PocketBase? That's a big step for many users, is it absolutely necessary?

**Comment by MRSessions** [comment]
hey @benallfree,

I'm glad you bring those questions up. Makes me think of how I can better explain things and document.

> "I'm not clear on what you mean by served from PocketBase (used as a Go framework/toolkit) as a backend. Is that different from served from PocketBase?"

For the first question, it doesn't have to be there, I wanted to try and give an idea that PocketBase/Go is being used to serve the Vue UI on build. Maybe I should reword that here and add a link to here

- https://pocketbase.io/docs/use-as-framework/ and
- https://github.com/pocketbase/pocketbase/blob/master/examples/base/main.go

on my README.md to better explain that.

*Words are hard sometimes, and I'm bad with summaries.*

> Also, just out of curiosity, why the custom build of PocketBase? That's a big step for many users, is it absolutely necessary?

For the second question, the idea is that anyone who uses the template doesn't have to really pick up on the custom PocketBase files. I'm trying to make that part as easy as possible. I wanted to be able to create a single Docker Container that would host an application with a robust BaaS DB, and PocketBase makes that possible.

After looking through, I really like the solution and PocketBase was something I had been looking for as a solution for a while. I wanted to cover up some of the "unnecessary" stuff for normal users who don't need to see the PocketBase UI at all, and to also reduce a potential attack service if this were something used in production. Also wanted to try and work out a couple of additional features as well.

In the end, the idea is to be able to quickly setup a robust PocketBase application using this template. An option has been added to enable or disable the PocketBase UI via a Docker or Docker Compose environment variable to allow a developer to develop their schema, turn off the UI, and deploy the app as discussed here [pocketbase-vue-starter/issues/10](https://github.com/MRSessions/pocketbase-vue-starter/issues/10#issuecomment-1439359268)

It will also be easily possible to take just the `vue-client` portion of the app and connect it to a separate PocketBase instance if that is the desired intent, and something I plan to document soon.

Sorry for the wall of text, hopefully it's not overload.

Honestly, it's been a learning adventure for me with this being my true first time diving into the Go language. I'm learning a lot in the little I have done with it.

**Comment by benallfree** [comment]
> It will also be easily possible to take just the vue-client portion of the app and connect it to a separate PocketBase instance if that is the desired intent, and something I plan to document soon.

Yes, this seems to be the essence of the starter kit and what I would emphasize in the docs and link description. The custom PocketBase build and hosting the frontend using PocketBase are secondary and less common needs that seem like they don't belong in the starter kit except for maybe mentioning in the readme.

Just my humble opinion :)

**Comment by benallfree** [comment]
@MRSessions What is the status of this PR? Are your ready to merge?

**Comment by benallfree** [comment]
Closing due to inactivity

**Pull request closed without merging**
