### PR TITLE
Add NextJS starter template

### PR DESCRIPTION
**Pull request by tsensei**
This is a NextJS starter template (app router) for Pocketbase supporting SSR. Pocketbase uses localstorage to store auth token so it isn't accessible by server components / middleware by default. It is discussed in details in this issue [#69](https://github.com/pocketbase/js-sdk/issues/69). This template aims to solve it.

- Contains a script for automatic pocketbase setup
- Script included for type generation using `pnpm typegen`
- Exports `createServerClient` & `createBrowserClient` for client component and server component interaction

### CODE REVIEW

**Comment by benallfree** [comment]
Unfortunately as per the [awesome guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md?plain=1#L43) your project must be around for 30 days before inclusion. I'm going to close this PR for now but please consider re-opening it or making a new one after 30 days.

**Comment by benallfree** [comment]
I'm sorry, I misread the rules. Your submission is fine :) 

I see two separate entries here, did you mean to do that?

**Comment by tsensei** [comment]
I am seeing only one ?

**Comment by benallfree** [comment]
Changes under React and Vue sections

**Comment by benallfree** [comment]
Oh I see, it's a whitespace issue. Sorry. Slow day. Was that change intended?

**Comment by tsensei** [comment]
Sorry, I think my formatter changed some whitespaces.

**Comment by benallfree** [comment]
Thank you! 🍕

**Pull request merged**
