### PR TITLE
Add PocketBase plugins section

### PR DESCRIPTION
**Pull request by iamelevich**
Add Plugins sections with my plugins. Probably can be useful for someone.

### CODE REVIEW

**Comment by benallfree** [comment]
Hi, thanks for submitting this! :)

I'm not sure I understand the purpose of this plugin, can you provide a use case to explain?

**Comment by iamelevich** [comment]
> Hi, thanks for submitting this! :)
> 
> I'm not sure I understand the purpose of this plugin, can you provide a use case to explain?

Sure. There are 3 plugins:

## Telegram auth plugin

Add route that implements auth with Telegram.

### Use cases
- If you want to add Login with Telegram button to website with PocketBase backend.
- If you want to create Telegram WebApp with PocketBase backend. Let you validate and auth users easily

## Ngrok plugin

Add ability to use [ngrok](https://ngrok.com/) for PocketBase application easily. Basically creates tunnel that makes your app avalilable with https or http in internet.

### Use cases

- If you want to test your app with mobile device over internet without deploying or sharing in local network. Just use this plugin and it will give you https link that will be available through the internet.
- You need to test with tool that accepts only https (For example if you are creating Telegram bot it accepts only https)

## Proxy plugin

Simple proxy for non PocketBase routes.

### Use cases

- You want to use separate server as your frontend, but want all of them be available with the same port. For example you have frontend with Next.js and want to test everything with mobile device. You can use proxy plugin to proxify all non PocketBase requests to the Next.js server and ngrok plugin to expose everything to the internet and test with mobile device.

@benallfree Is it clear enough? Probably make sense to update description in the PR somehow?

**Comment by benallfree** [comment]
1. I'm kind of stumbling over the term `plugin` - does PocketBase have an official Plugin API? 
2. Telegram - makes sense!
3. ngrok - I'm not understanding why it's necessary. Can't users just run the `ngrok` CLI tool? What am I missing :)
4. proxy - From what I can gather, you are using ngrok to create a single entry point so you can test from your mobile device, then this proxy plugin routes requests to next.js or pocketbase based on routing rules, right? This is an interesting solution, but it requires making a custom build of PocketBase. I imagine there are many lightweight proxy apps that can be used for dev purposes, have you considered that approach? For example, https://www.npmjs.com/package/local-web-server

**Comment by benallfree** [comment]
Okay, I understand now. Thank you!

**Pull request merged**
