### PR TITLE
Update Repo for Adherence With awesome-lint

### PR DESCRIPTION
**Pull request by jorgoose**
Since this repo seems to be generally following the structure of the "Awesome" project (https://github.com/sindresorhus/awesome), I went ahead and made changes to the README that adhere to the guidelines outlined at https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md.

Adherence to guidelines was validated running the Awesome linter via "npx awesome-lint README.md".

With these changes, this repo should be able to be added to https://github.com/sindresorhus/awesome/blob/main/readme.md in a PR.

### CODE REVIEW

**Comment by benallfree** [comment]
This is so incredibly generous and helpful! I have to admit, I didn't even understand that there was an "awesome" format or hub of any kind, I thought it was just a loose ethos.

So after making these changes, we can submit a PR to get it included in the main directory?

**Comment by jorgoose** [comment]
Yep. I was looking at the main "Awesome" repo and noticed that PocketBase was not on there. The repo has 280k+ stars, and lots of newbies interested in programming / software engineering come across that repo. 

I think it would be "awesome" (pun intended) if we got PocketBase on there!

And yes, the PR guidelines are here: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

**Comment by benallfree** [comment]
⭐ for @jorgoose!

**Comment by benallfree** [comment]
@jorgoose would you be willing to do the PR to awesome, or does that feel a little out of scope? We'd love the help if you are able.

**Comment by jorgoose** [comment]
@benallfree Yeah I'm more than willing to. I can open the PR within the next day or so, will need to do reviews as per their guidelines.

**Comment by jorgoose** [comment]
Update: PR is opened, but looks like it didn't meet all of the guidelines. Working on double checking everything at the moment but a second pair of eyes could help:

https://github.com/sindresorhus/awesome/pull/2895

**Comment by benallfree** [comment]
I just looked through everything and didn't spot any issues either. Do we know what they are running to determine things were missed? Or was this a human review?

**Pull request merged**
